#!/bin/bash

qemu-system-x86_64 -enable-kvm -m 4G -smp 2 \
	-hda newdisk.qcow2 \
	-cdrom ubuntu.iso \
	-net nic \
	-net user \
	-device usb-ehci -device usb-kbd \
	-nographic
	

	#-net bridge,br=br1 \
#-nographic -serial mon:stdio -display none
#-boot c  \
#-display curses -vga none -nographic
#-cdrom ubuntu.iso \
#-netdev user,id=net0 -device virtio-net-pci,netdev=net0
